### ISSUE TITLE
ubuntu18.04下启动celery worker时报错称DBUtils模块找不到

### ISSUE THREAD

**Issue by Hongjiao1999** [hanc00l/nemo#2]
![图片](https://user-images.githubusercontent.com/38355651/110231233-7cee4280-7f51-11eb-9b32-638a853690ba.png)
pip已经拉了DBUtils这个模块，报错原因百度是说版本不同导致import包时候的写法不同，但是我改变写法还是报错，请问师傅有遇到这个情况吗

**Comment by hanc00l** [comment]
用python写稍微大点的项目时，就会遇到令人头痛的依赖包的问题，经过一番被折腾得精疲力尽后，目前使用python3.7+mysql5.7+DBUtils==1.4+celery==4.4.7的组合能确保相对稳定运行。你安装的问题就是因为版本的问题。你pip安装使用pip install -r requirements.txt，确保安装指定的版本。另外，在linux下安装的话建议使用linux_install.sh。
