### ISSUE TITLE
容器部署运行进入5000端口平台里，点击ip和域名资产自动登出，无法新建任务

### ISSUE THREAD

**Issue by Hongjiao1999** [hanc00l/nemo#3]

**Comment by hanc00l** [comment]
我刚docker build 和docker run，并测试了一下并没有问题，所以不知道你的问题原因；你可以看看nemo的运行日志，有什么报错情况。
docker exec -it container_id /bin/bash
/opt/nemo# tail -f nohup.out instance/*.log

<img width="1552" alt="截屏2021-03-07 20 57 18" src="https://user-images.githubusercontent.com/12759172/110240798-8c3cb280-7f88-11eb-852d-9cae4859c042.png">
<img width="1552" alt="截屏2021-03-07 20 58 00" src="https://user-images.githubusercontent.com/12759172/110240818-a7a7bd80-7f88-11eb-9a02-11cd6747c125.png">

**Comment by Hongjiao1999** [comment]
![图片](https://user-images.githubusercontent.com/38355651/110241022-9f9c4d80-7f89-11eb-9a16-ceae4d297679.png)

**Comment by hanc00l** [comment]
看起来没有报错之类的，不知道浏览器是不是用的chrome或firefox？

**Comment by Hongjiao1999** [comment]
是的，我这个是Ubuntu虚拟机，两个浏览器都试过了，师傅可否加联系方式

**Comment by hanc00l** [comment]
麻烦你留一下微信或QQ号，明天我加你。

**Comment by Hongjiao1999** [comment]
好的，谢谢师傅。
qq:493636927,wx:hongjiao1999。

**Comment by jackey815** [comment]
访问ip-list 和 domain-list 返回302，直接跳转至主页了么，我也碰到类似的问题

**Comment by jackey815** [comment]
请问后续怎么解决的

**Comment by Hongjiao1999** [comment]
> 
> 
> 访问ip-list 和 domain-list 返回302，直接跳转至主页了么，我也碰到类似的问题

这个项目使用了子模块，在/nemo/common/thirdparty/下有两个子模块需要获取，使用`git clone --recursive https://github.com/hanc00l/nemo`来拉取完整项目

**Comment by hanc00l** [comment]
@jackey815 因为项目使用了两个子仓库，一个是xray，一个是some_pocsuite，如果不是用的git clone --recursive 或者没有完全拉取这两子库的话，就会报错。上次是这个原因引起的。
