### ISSUE TITLE
请问如何新建扫描任务

### ISSUE THREAD

**Issue by jackey815** [hanc00l/nemo#4]
请问如何新建一个扫描任务？

**Comment by hanc00l** [comment]
登录后在IP（或者Domain）中 -> “新建任务”。
<img width="1552" alt="截屏2021-03-29 09 01 45" src="https://user-images.githubusercontent.com/12759172/112774849-8c067300-906d-11eb-98a1-f75d0eba3d80.png">
<img width="1552" alt="截屏2021-03-29 09 01 54" src="https://user-images.githubusercontent.com/12759172/112774867-932d8100-906d-11eb-9fa3-bca345ff6b19.png">
